-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 19:47:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Movies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Movies` ;

-- -----------------------------------------------------
-- Schema Movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Movies` DEFAULT CHARACTER SET utf8 ;
USE `Movies` ;

-- -----------------------------------------------------
-- Table `Movies`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movies`.`ratings` ;

CREATE TABLE IF NOT EXISTS `Movies`.`ratings` (
  `tconst` VARCHAR(45) NOT NULL,
  `average_rating` FLOAT NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movies`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movies`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `Movies`.`title_basics` (
  `tconst` VARCHAR(45) NOT NULL,
  `primary_title` VARCHAR(45) NULL,
  `start_year` FLOAT NULL,
  `runtime` INT NULL,
  `ratings_tconst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tconst`, `ratings_tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movies`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movies`.`genres` ;

CREATE TABLE IF NOT EXISTS `Movies`.`genres` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Movies`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Movies`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `Movies`.`title_genres` (
  `tconst` VARCHAR(45) NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`tconst`, `genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
